source 'https://rubygems.org'
ruby '2.3.1'

gem 'minitest'
gem 'minitest-ci'
gem 'rake', '~> 11.1', '>= 11.1.2'
gem 'abstract_method', '~> 1.2', '>= 1.2.1'
gem 'mocha'
gem 'rubyzip'
gem 'httparty', '~> 0.13.7'
gem 'roo', '~> 2.7.0'
gem 'roo-xls'
